#pragma once

void AgeCalculate();
void TaxiFeeCalculate();
void SumDigitCalculateUseString();
void SumDigitCalculateUseArithmetic();
void CheckSymmetricNumberUseString();
void CheckSymmetricNumberUseArithmetic();
void CountDigitUseString();
void CountDigitUseArithmetic();
void FindFactorial();
void FindFactorialRecursive();
void CheckNarcissisticNumber();
void FindLeapYears();
void CheckValidDay();
void FindPreviousDay();
void FindNextDay();
void FindOrderOfDay();
void CheckPrimeInteger();
void FindGreatestCommonDivisor();
void CountDivisor();
void CheckPerfectInteger();
void CalculateSn();